2022-04-07T14:03:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:06|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:07|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:08|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
2022-04-07T14:04:09|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: too many indices for array: array is 2-dimensional, but 3 were indexed. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 351, in update_display\n    saturation = image[:,:,:3].max() / 255.0\n', 'IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed\n']
